### ISSUE TITLE
Can't install the web package

### ISSUE THREAD

**Issue by DorianMaliszewski** [panz3r/react-keycloak#87]
**Describe the bug**
The package is not found on the npm registry.

**To Reproduce**

1. Go to your terminal
2. Make `yarn add @react-keycloak/web`
3. See error

**Expected behavior**
Find the package

**Screenshots**

```
$ > yarn add @react-keycloak/web
yarn add v1.19.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-keycloak%2fweb: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/dorian/Projects/Hospitalink/frontend-v2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

yarn-error.log
```
Trace: 
  Error: https://registry.yarnpkg.com/@react-keycloak%2fweb: Not found
      at Request.params.callback [as _callback] (/usr/lib/node_modules/yarn/lib/cli.js:66927:18)
      at Request.self.callback (/usr/lib/node_modules/yarn/lib/cli.js:140586:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:141558:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:141480:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1221:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Desktop (please complete the following information):**

- OS: Manjaro Linux 5.4
- Node version : 12.17.0
- Npm version : 6.14.6
- Yarn version : 1.19.2

**Comment by panz3r** [comment]
Hi @DorianMaliszewski ,

Thanks for your feedback, it seems there's an ongoing incident with npmjs.com and the retrieval of scoped packages, see here for more details 
[https://status.npmjs.org/incidents/cksjqc1w11v5](https://status.npmjs.org/incidents/cksjqc1w11v5)

**Comment by DorianMaliszewski** [comment]
You was right thanks
